routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\MasterBarangController;
use App\Http\Controllers\TransaksiBarangController;
use App\Http\Controllers\CrudUserController;
use phpDocumentor\Reflection\Types\Resource_;
use App\Http\Controllers\HomeController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Halaman Awal
Route::get('/', function () {
    return view('welcome');
});

Route::get('index', function () {
    return view('admin/index');
});
Route::get('tes', function () {
    return view('tes/tes');
});

Auth::routes();

Route::group(['middleware' => ['web']], function () {

    Route::get('/home', [HomeController::class, 'index'])->name('home');

    // CRUD User
    Route::resource('/CrudUser', CrudUserController::class)->middleware('CekRole:admin');

    //Barang
    Route::get('/barang/barang_pdf', [MasterBarangController::class, 'barang_pdf'])->name('barang_pdf');
    Route::resource('/barang', MasterBarangController::class)->middleware('CekRole:admin');

    //Transaksi
    Route::get('/transaksi/transaksibarang_pdf/{id}', [TransaksiBarangController::class, 'transaksibarang_pdf'])->name('transaksibarang_pdf');
    Route::get('/transaksi/transaksi_pdf', [TransaksiBarangController::class, 'transaksi_pdf'])->name('transaksi_pdf');
    Route::resource('/transaksi', TransaksiBarangController::class);

});

app/Http/Controllers/TransaksiBarangController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\TransaksiPembelianBarang;
use App\Models\TransaksiPembelian;
use App\Models\Barang;
use PDF;

class TransaksiBarangController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $Transaksi = TransaksiPembelian::all();
        return view('TransaksiBarang.index', compact('Transaksi'));
    }
    public function show($id)
    {
        $Transaksi = TransaksiPembelian::find($id);

        return view('TransaksiBarang.show', compact('Transaksi'));
    }

    public function create()
    {
        $Transaksi = TransaksiPembelian::all();
        $TransaksiBarang = TransaksiPembelianBarang::all();
        $barang = Barang::all();


        return view('TransaksiBarang.create', compact('Transaksi', 'TransaksiBarang', 'barang'));
    }

    public function store(Request $request)
    {
        $request->validate([
            'transaksi_pembelian_id' => 'required',
            'master_barang_id' => 'required',
            'jumlah' => 'required',
            'harga_satuan' => 'required',
        ]);

        $kapasitas = [
            "transaksi_pembelian_id" => $request["transaksi_pembelian_id"],
            "master_barang_id" => $request["master_barang_id"],
            "jumlah" => $request["jumlah"],
            "harga_satuan" => $request["harga_satuan"],
        ];
        $total_harga = $request["jumlah"] * $request["harga_satuan"];

        if ($kapasitas["transaksi_pembelian_id"] == 0) {
            $transaksi_pembelian = TransaksiPembelian::create([
                "total_harga" => $total_harga,
            ]);

            TransaksiPembelianBarang::create([
                "transaksi_pembelian_id" => $transaksi_pembelian->id,
                "master_barang_id" => $kapasitas["master_barang_id"],
                "jumlah" => $kapasitas["jumlah"],
                "harga_satuan" => $kapasitas["harga_satuan"]
            ]);
            return redirect('/transaksi');
        } elseif ($kapasitas["transaksi_pembelian_id"] > 1) {
            $transaksi_pembelian = TransaksiPembelian::find($kapasitas["transaksi_pembelian_id"]);
            $transaksi_pembelian->total_harga += $total_harga;
            $transaksi_pembelian->save();

            TransaksiPembelianBarang::create([
                "transaksi_pembelian_id" => $transaksi_pembelian->id,
                "master_barang_id" => $kapasitas["master_barang_id"],
                "jumlah" => $kapasitas["jumlah"],
                "harga_satuan" => $kapasitas["harga_satuan"]
            ]);
            return redirect('/transaksi');
        }
    }

    public function edit($id)
    {
        $Transaksi = TransaksiPembelian::all();
        $TransaksiBarang = TransaksiPembelianBarang::find($id);
        $barang = Barang::all();

        return view('TransaksiBarang.edit', compact('Transaksi', 'TransaksiBarang', 'barang'));
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'transaksi_pembelian_id' => 'required',
            'master_barang_id' => 'required',
            'jumlah' => 'required',
            'harga_satuan' => 'required',
        ]);

        $cariTransaksiBarang = TransaksiPembelianBarang::find($id);

        $kapasitas = [
            "transaksi_pembelian_id" => $request["transaksi_pembelian_id"],
            "master_barang_id" => $request["master_barang_id"],
            "jumlah" => $request["jumlah"],
            "harga_satuan" => $request["harga_satuan"],
        ];

        $TransaksiBarang = TransaksiPembelianBarang::find($kapasitas['transaksi_pembelian_id']);
        $TransaksiP = TransaksiPembelian::find($kapasitas['transaksi_pembelian_id']);

        $total_harga_baru = $request["jumlah"] * $request["harga_satuan"];
        $total_harga_lama = $TransaksiBarang["jumlah"] * $TransaksiBarang["harga_satuan"];

        if ($total_harga_baru > $total_harga_lama) {
            $total_harga = $total_harga_baru - $total_harga_lama;
            $totalHarga = ($TransaksiP['total_harga'] + $total_harga);
            $transaksi_pembelian = [
                "total_harga" => $totalHarga
            ];
            $TransaksiP->update($transaksi_pembelian);
            $cariTransaksiBarang->update($kapasitas);

            return redirect('/transaksi/');
        } elseif ($total_harga_baru < $total_harga_lama) {
            $total_harga = $total_harga_lama - $total_harga_baru;
            $totalHarga = ($TransaksiP['total_harga'] - $total_harga);
            $transaksi_pembelian = [
                "total_harga" => $totalHarga
            ];
            $TransaksiP->update($transaksi_pembelian);
            $cariTransaksiBarang->update($kapasitas);

            return redirect('/transaksi/');
        } elseif ($total_harga_baru == $total_harga_lama) {
            return redirect('/transaksi/');
        }
        redirect('/transaksi');
    }

    public function destroy($id)
    {
        $TransaksiBarang = TransaksiPembelianBarang::find($id);
        $Transaksi = TransaksiPembelian::find($TransaksiBarang["transaksi_pembelian_id"]);

        $total_harga = $TransaksiBarang["jumlah"] * $TransaksiBarang["harga_satuan"];
        $totalHarga = $Transaksi["total_harga"] - $total_harga;

        $transaksi_pembelian = [
            "total_harga" => $totalHarga
        ];

        $Transaksi->update($transaksi_pembelian);
        $TransaksiBarang->delete();

        if ($Transaksi['total_harga'] == 0) {
            $Transaksi->delete();
        }

        return redirect('/transaksi');
    }
    public function transaksi_pdf()
    {
    	$transaksi = TransaksiPembelian::all();

    	$pdf = PDF::loadview('TransaksiBarang.transaksi_pdf', compact('transaksi'));
    	return $pdf->stream('laporan-transaksi.pdf');
    }
    public function transaksibarang_pdf($id)
    {
        $Transaksi = TransaksiPembelian::find($id);

    	$pdf = PDF::loadview('TransaksiBarang.transaksibarang_pdf', compact('Transaksi'));
    	return $pdf->stream('laporan-transaksibarang.pdf');
    }

}

resources/views/TransaksiBarang/create.blade.php
@extends("layouts.master")
@section('title')
    Halaman Create Barang
@endsection
@section('nama')
    Faisal Dzulfikar
@endsection
@section('judul')
    Halaman Create Barang
@endsection
@section('content')

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Create Barang</h6>
        </div>
        <div class="card-body">
            <form action="/transaksi" method="POST">
                @csrf
                <div class="form-group">
                    <label for="exampleFormControlSelect1">Nomer Transaksi Barang</label>
                    <select class="form-control" id="exampleFormControlSelect1" name="transaksi_pembelian_id">
                        <option> Pilih ID Transaksi atau Tambah Transaksi</option>
                        <option value="0" class="font-weight-bold"> Pilih ID Transaksi atau Tambah Transaksi</option>
                        @foreach ($Transaksi as $item)
                            <option class="font-weight-bold" value="{{ $item->id }}">
                                {{ $item->id }}</option>
                        @endforeach
                    </select>
                </div>
                {{-- Form Barang --}}
                <div class="form-group">
                    <label for="exampleFormControlSelect1">Nama Barang</label>
                    <select class="form-control" id="exampleFormControlSelect1" name="master_barang_id">
                        <option>-- Pilih Barang --</option>
                        @foreach ($barang as $item)
                            <option value="{{ $item->id }}" class="font-weight-bold">
                                {{ $item->nama_barang }}/{{ $item->harga_satuan }}</option>
                        @endforeach
                    </select>
                </div>
                {{-- Kuantitas --}}
                <div class="form-group">
                    <label for="jumlah">Jumlah</label>
                    <input type="number" class="form-control" name="jumlah" id="jumlah"
                        placeholder="Masukkan Jumlah Data Yang Dibeli">
                    @error('jumlah')
                        <div class="alert alert-danger">
                            {{ $message }}
                        </div>
                    @enderror
                </div>
                 {{-- Harga Satuan--}}
                <div class="form-group">
                    <label for="harga_satuan">Harga Satuan</label>
                    <input type="number" class="form-control" name="harga_satuan" id="harga_satuan"
                        placeholder="Masukkan Harga Satuan">
                    @error('harga_satuan')
                        <div class="alert alert-danger">
                            {{ $message }}
                        </div>
                    @enderror
                </div>
                <button type="submit" class="btn btn-primary">Tambah</button>
            </form>
        </div>
    </div>
@endsection

resources/views/TransaksiBarang/edit.blade.php
@extends("layouts.master")
@section('title')
    Halaman Edit Barang
@endsection
@section('nama')
    Faisal Dzulfikar
@endsection
@section('judul')
    Halaman Edit Barang
@endsection
@section('content')

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Edit Barang</h6>
        </div>
        <div class="card-body">
            <form action="/transaksi/{{ $TransaksiBarang->id }}" method="POST">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <input type="number" class="form-control" name="transaksi_pembelian_id" id="transaksi_pembelian_id"
                        value="{{ $TransaksiBarang->id }}" placeholder="Masukkan Transaksi Pembelian ID" hidden>
                    <label for="exampleFormControlSelect1">Nama Barang</label>
                    <select class="form-control" id="exampleFormControlSelect1" name="master_barang_id">
                        <option selected>-- Pilih Menu Barang --</option>
                        @foreach ($barang as $item)
                        @if ($item->id === $TransaksiBarang->master_barang_id )
                        <option value="{{ $item->id }}" selected>{{ $item->nama_barang }} / {{ $item->harga_satuan }}</option>
                        @else
                        <option value="{{ $item->id }}">{{ $item->nama_barang }} / {{ $item->harga_satuan }}</option>
                        @endif
                        @endforeach
                        @error('master_barang_id')
                        <div class="alert alert-danger">
                            {{ $message }}
                        </div>
                        @enderror
                    </select>
                </div>
                <div class="form-group">
                    <label for="jumlah">Jumlah</label>
                    <input type="number" class="form-control" name="jumlah" id="jumlah" placeholder="Masukkan Harga Satuan"
                        value="{{ $TransaksiBarang->jumlah }}">
                    @error('jumlah')
                    <div class="alert alert-danger">
                        {{ $message }}
                    </div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="harga_satuan">Harga Satuan</label>
                    <input type="number" class="form-control" name="harga_satuan" id="harga_satuan"
                        placeholder="Masukkan Harga Satuan" value="{{ $TransaksiBarang->harga_satuan }}">
                    @error('harga_satuan')
                    <div class="alert alert-danger">
                        {{ $message }}
                    </div>
                    @enderror
                </div>
                <button type="submit" class="btn btn-primary">Edit</button>
            </form>
        </div>
    </div>
@endsection

resources/views/TransaksiBarang/index.blade.php
@extends("layouts.master")
@push('style')

    <!-- Custom styles for this page -->
    <link href="{{ asset('sb_admin_2') }}/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
@endpush
@section('title')
    Halaman Transaksi Barang
@endsection
@section('nama')
    Faisal Dzulfikar
@endsection
@section('judul')
    Halaman Transaksi Barang
@endsection
@section('content')
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Transaksi Barang</h6>
            </div>
            <div class="card-body">
                <a href="/transaksi/create" class="btn btn-primary" target="_blank">Tambah +</a>
                <a href="/transaksi/transaksi_pdf" class="btn btn-primary" target="_blank">Cetak PDF</a>
                <br>
                <br>
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>ID Transaksi</th>
                                <th>Total Harga Transaksi</th>
                                <th>Waktu Dibuat</th>
                                <th>Waktu Diupdate</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>No</th>
                                <th>ID Transaksi</th>
                                <th>Total Harga Transaksi</th>
                                <th>Waktu Dibuat</th>
                                <th>Waktu Diupdate</th>
                                <th>Aksi</th>
                            </tr>
                        </tfoot>
                        <tbody>
                            @foreach ($Transaksi as $item => $key)
                                <tr>
                                    <td>{{ $item + 1 }}</td>
                                    <td>{{ $key->id }}</td>
                                    <td>{{ $key->total_harga }}</td>
                                    <td>{{ $key->created_at }}</td>
                                    <td>{{ $key->updated_at }}</td>
                                    <td class="text-center">
                                    <a href="transaksi/{{$key->id}}" class="btn btn-info">Cek Detail</a>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>
    <!-- /.container-fluid -->

@endsection

@push('script')
    <!-- Page level plugins -->
    <script src="{{ asset('sb_admin_2') }}/vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="{{ asset('sb_admin_2') }}/vendor/datatables/dataTables.bootstrap4.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="{{ asset('sb_admin_2') }}/js/demo/datatables-demo.js"></script>
@endpush

resources/views/TransaksiBarang/show.blade.php
@extends("layouts.master")
@section('title')
    Halaman Show Transaksi Barang
@endsection
@section('nama')
    Faisal Dzulfikar
@endsection
@section('judul')
    Halaman Show Transaksi Barang
@endsection
@section('content')

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Show Barang</h6>
        </div>
        <div class="card-body">
            <a href="/transaksi/transaksibarang_pdf/{{$Transaksi->id}}" class="btn btn-primary" target="_blank" >Cetak PDF</a>
            <h2 align="center">ID Transaksi {{ $Transaksi->id }}</h2>
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Nama Barang</th>
                        <th>Harga Satuan</th>
                        <th>Jumlah Barang</th>
                        <th>Jumlah Harga Barang</th>
                        <th>Waktu Dibuat</th>
                        <th>Waktu Diupdate</th>
                        <th>Aksi</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <td>Total Transaksi</td>
                        <td colspan="7" align="center">{{ $Transaksi->total_harga }}</td>
                    </tr>
                </tfoot>
                <tbody>
                    @foreach ($Transaksi->transaksi_pembelian_barang as $item => $key)
                        <tr>
                            <td>{{ $item + 1 }}</td>
                            <td>{{ $key->master_barang->nama_barang }}</td>
                            <td>{{ $key->harga_satuan }}</td>
                            <td>{{ $key->jumlah }}</td>
                            <td>{{ $key->harga_satuan * $key->jumlah }}</td>
                            <td>{{ $key->created_at }}</td>
                            <td>{{ $key->updated_at }}</td>
                            <td>
                                <a href="{{ route('transaksi.edit', $key->id) }}" class="btn btn-warning">Edit</a>
                                <form action="{{ route('transaksi.destroy', $key->id) }}" method="post"
                                    class="d-inline">
                                    @csrf
                                    @method('delete')
                                    <button class="btn btn-danger" type="submit">Delete</button>
                                </form>
                        </tr>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection

resources/views/TransaksiBarang/transaksi_pdf.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Laporan Transaksi</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
	<style type="text/css">
		table tr td,
		table tr th{
			font-size: 9pt;
		}
	</style>
	<center>
		<h4>Laporan Data Transaksi</h4>
	</center>

	<table class='table table-bordered'>
		<thead>
            <tr>
                <th>No</th>
                <th>ID Transaksi</th>
                <th>Total Harga</th>
                <th>Waktu Dibuat</th>
                <th>Waktu Diperbarui</th>
            </tr>
		</thead>
		<tbody>
			@foreach($transaksi as $item => $key)
            <tr>
                <td>{{ $item + 1 }}</td>
                <td>{{ $key->id }}</td>
                <td>{{ $key->total_harga }}</td>
                <td>{{ $key->created_at }}</td>
                <td>{{ $key->updated_at }}</td>
            </tr>
			@endforeach
		</tbody>
	</table>

</body>
</html>

resources/views/TransaksiBarang/transaksibarang_pdf.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Laporan Transaksi Barang</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
	<style type="text/css">
		table tr td,
		table tr th{
			font-size: 9pt;
		}
	</style>
	<center>
		<h4>Laporan Data Transaksi Barang</h4>
            <h5>ID Transaksi : {{$Transaksi->id}}</h5>
	</center>

	<table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
            <tr>
                <th>No</th>
                <th>Nama Barang</th>
                <th>Harga Satuan</th>
                <th>Jumlah Barang</th>
                <th>Jumlah Harga Barang</th>
                <th>Waktu Dibuat</th>
                <th>Waktu Diupdate</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($Transaksi->transaksi_pembelian_barang as $item => $key)
                <tr>
                    <td>{{ $item + 1 }}</td>
                    <td>{{ $key->master_barang->nama_barang }}</td>
                    <td>{{ $key->harga_satuan }}</td>
                    <td>{{ $key->jumlah }}</td>
                    <td>{{ $key->harga_satuan * $key->jumlah }}</td>
                    <td>{{ $key->created_at }}</td>
                    <td>{{ $key->updated_at }}</td>
                </tr>
                </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr>
                <td>Total Transaksi</td>
                <td colspan="7" align="center">{{ $Transaksi->total_harga }}</td>
            </tr>
        </tfoot>
    </table>

</body>
</html>